### ISSUE TITLE
facing error while running the plugin in the local development env

### ISSUE THREAD

**Issue by Msarawan** [artemiscloud/activemq-artemis-self-provisioning-plugin#126]
when i run the plugin getting the below issues in the console.

![Screenshot from 2024-04-24 13-25-53](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/assets/99248895/c24fbbcc-e0e8-43cc-b2cd-dae2125e55f4)

**Comment by lavocatt** [comment]
Here's the full stack of the issue:

```
TypeError
Description:
Cannot read properties of undefined (reading 'deploymentPlan')

Component trace:
at BrokerRow (http://localhost:9000/api/plugins/activemq-artemis-self-provisioning-plugin/exposed-BrokersPage-chunk.js:117:22)
    at Row (http://localhost:9000/api/plugins/activemq-artemis-self-provisioning-plugin/exposed-BrokersPage-chunk.js:186:263)
    at http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1202790
    at tr
    at T (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:676004)
    at t (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:168:12638)
    at tbody
    at table
    at m (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:260:150410)
    at s (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:265:125727)
    at t.a (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1202868)
    at div
    at div
    at t (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:116:71685)
    at t (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:115:34070)
    at o (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:686865)
    at div
    at div
    at w (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:117571)
    at S (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:118019)
    at div
    at t.default (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:177844)
    at BrokersTable (http://localhost:9000/api/plugins/activemq-artemis-self-provisioning-plugin/exposed-BrokersPage-chunk.js:158:25)
    at div
    at t.a (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:960013)
    at BrokersList (http://localhost:9000/api/plugins/activemq-artemis-self-provisioning-plugin/exposed-BrokersPage-chunk.js:188:24)
    at BrokersContainer (http://localhost:9000/api/plugins/activemq-artemis-self-provisioning-plugin/exposed-BrokersPage-chunk.js:32:81)
    at t (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:21:69882)
    at A (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1273687)
    at t (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:21:71963)
    at Suspense
    at i (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:319766)
    at section
    at m (http://localhost:9000/static/vendor-patternfly-core-chunk-e4bca88d7e0a13a77e6c.min.js:1:246962)
    at div
    at div
    at t.a (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1273916)
    at div
    at div
    at l (http://localhost:9000/static/vendor-patternfly-core-chunk-e4bca88d7e0a13a77e6c.min.js:1:732090)
    at d (http://localhost:9000/static/vendor-patternfly-core-chunk-e4bca88d7e0a13a77e6c.min.js:1:297179)
    at div
    at d (http://localhost:9000/static/vendor-patternfly-core-chunk-e4bca88d7e0a13a77e6c.min.js:1:155222)
    at c (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1039545)
    at http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:294021
    at x (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:116:90482)
    at main
    at div
    at v (http://localhost:9000/static/vendor-patternfly-core-chunk-e4bca88d7e0a13a77e6c.min.js:1:529366)
    at div
    at div
    at l (http://localhost:9000/static/vendor-patternfly-core-chunk-e4bca88d7e0a13a77e6c.min.js:1:382825)
    at div
    at div
    at l (http://localhost:9000/static/vendor-patternfly-core-chunk-e4bca88d7e0a13a77e6c.min.js:1:732090)
    at d (http://localhost:9000/static/vendor-patternfly-core-chunk-e4bca88d7e0a13a77e6c.min.js:1:297179)
    at div
    at d (http://localhost:9000/static/vendor-patternfly-core-chunk-e4bca88d7e0a13a77e6c.min.js:1:155222)
    at Jn (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:58:172658)
    at t.default (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:789819)
    at e.default (http://localhost:9000/static/quick-start-chunk-749ede29cbe78d70d3e9.min.js:1:3537)
    at s (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:150069)
    at t.a (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1350707)
    at ee (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1370693)
    at xt (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:58:129794)
    at ee (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1370693)
    at ee (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1370693)
    at o (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:732518)
    at t.a (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1343127)
    at t.a (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1343316)
    at t.a (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1340802)
    at te (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1370815)
    at ne (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1372833)
    at t (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:21:69882)
    at t (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:21:71963)
    at P (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:58:4488)
    at ne (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:58:9932)
    at te (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:58:9341)
    at X (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:115:11631)
    at t (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:21:66312)
    at ae (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:1373095)
    at t.a (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:706782)
    at t.a (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:959650)
    at s (http://localhost:9000/static/main-chunk-d73c13a82ae55ca97d6e.min.js:1:510570)
    at t.a (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:168:195070)
    at Suspense
Stack trace:
TypeError: Cannot read properties of undefined (reading 'deploymentPlan')
    at BrokerRow (http://localhost:9000/api/plugins/activemq-artemis-self-provisioning-plugin/exposed-BrokersPage-chunk.js:119:87)
    at na (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:281:58879)
    at Hs (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:281:111315)
    at Sc (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:281:98327)
    at Cc (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:281:98255)
    at _c (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:281:98118)
    at pc (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:281:95105)
    at http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:281:44774
    at t.unstable_runWithPriority (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:289:3768)
    at Uo (http://localhost:9000/static/vendors~main-chunk-7c7933a72d466385bfd9.min.js:281:44551)
```

**Comment by Msarawan** [comment]
Closed as completed
