### ISSUE TITLE
Storybook build fails

### ISSUE THREAD

**Issue by AjayJagan** [artemiscloud/activemq-artemis-self-provisioning-plugin#24]
While trying to do `yarn build-storybook` or `yarn storybook` it fails with the following error

```ERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve '@console/dynamic-plugin-sdk/src/perspective/useActivePerspective' in '/Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/@openshift-console/dynamic-plugin-sdk/lib/api'
63% building 14/14 entries 3311/3393 dependencies 732/848 modulesinfo => Manager built (9.16 s)
ERR! ModuleNotFoundError: Module not found: Error: Can't resolve '@console/dynamic-plugin-sdk/src/perspective/useActivePerspective' in '/Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/@openshift-console/dynamic-plugin-sdk/lib/api'
ERR!     at /Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/lib/Compilation.js:2016:28
ERR!     at /Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/lib/NormalModuleFactory.js:798:13
ERR!     at eval (eval at create (/Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
ERR!     at /Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/lib/NormalModuleFactory.js:270:22
ERR!     at eval (eval at create (/Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
ERR!     at /Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/lib/NormalModuleFactory.js:434:22
ERR!     at /Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/lib/NormalModuleFactory.js:116:11
ERR!     at /Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/lib/NormalModuleFactory.js:670:25
ERR!     at /Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/lib/NormalModuleFactory.js:855:8
ERR!     at /Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/lib/NormalModuleFactory.js:975:5
ERR!     at /Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/neo-async/async.js:6883:13
ERR!     at /Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/lib/NormalModuleFactory.js:958:45```

**Comment by AjayJagan** [comment]
maybe related: https://github.com/openshift/console/issues/12255

**Comment by lavocatt** [comment]
We no longer use storybook, clossing the issue.
